"""
NOVA_CORE — PDF Generator
Generación de documentos PDF profesionales para DJs (Tech Riders, Invoices).
"""

import os
from fpdf import FPDF
from datetime import datetime

class PDFGenerator:
    def __init__(self):
        self.output_dir = "data/pdf_exports"
        os.makedirs(self.output_dir, exist_ok=True)

    def create_tech_rider_pdf(self, dj_name: str, content: str) -> str:
        """Genera un PDF minimalista con el Tech Rider."""
        pdf = FPDF()
        pdf.add_page()
        
        # Configuración de diseño
        pdf.set_font("Helvetica", "B", 24)
        pdf.set_text_color(20, 20, 20)
        
        # Header
        pdf.cell(0, 20, "TECHNICAL RIDER", ln=True, align="L")
        pdf.set_font("Helvetica", "", 12)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 10, f"Artist: {dj_name.upper()}", ln=True, align="L")
        pdf.cell(0, 10, f"Date: {datetime.now().strftime('%d/%m/%Y')}", ln=True, align="L")
        
        pdf.ln(10)
        pdf.set_draw_color(200, 200, 200)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(10)
        
        # Content
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(40, 40, 40)
        
        # Dividir contenido por líneas para manejar saltos de página automáticos
        # fpdf2 maneja multi_cell bien
        pdf.multi_cell(0, 7, content)
        
        # Footer
        pdf.set_y(-30)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 10, "Generated by Nova Promo Hub — Professional DJ Ecosystem", align="C")
        
        filename = f"TechRider_{dj_name.replace(' ', '_')}_{datetime.now().strftime('%Y%m%d%H%M')}.pdf"
        filepath = os.path.join(self.output_dir, filename)
        pdf.output(filepath)
        
        return filepath

# Instancia única
pdf_manager = PDFGenerator()
